# Generated by Django 6.0.5 on 2026-07-06 13:28

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0236_moduletype_component_counts'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('virtualization', '0056_virtualmachine_render_config_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('zabbix_hostid', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('visible_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='enabled', max_length=20)),
                ('in_maintenance', models.BooleanField(default=False)),
                ('agent_available', models.CharField(default='unknown', max_length=10)),
                ('snmp_available', models.CharField(default='unknown', max_length=10)),
                ('ipmi_available', models.CharField(default='unknown', max_length=10)),
                ('jmx_available', models.CharField(default='unknown', max_length=10)),
                ('active_available', models.CharField(default='unknown', max_length=10)),
                ('proxy_name', models.CharField(blank=True, max_length=200)),
                ('host_groups', models.JSONField(blank=True, default=list)),
                ('templates', models.JSONField(blank=True, default=list)),
                ('interfaces', models.JSONField(blank=True, default=list)),
                ('match_method', models.CharField(default='none', max_length=20)),
                ('problem_count', models.PositiveIntegerField(default=0)),
                ('max_severity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zabbix_hosts', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zabbix_hosts', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'Zabbix host',
                'verbose_name_plural': 'Zabbix hosts',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ZabbixProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('zabbix_eventid', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('severity', models.PositiveSmallIntegerField(default=0)),
                ('acknowledged', models.BooleanField(default=False)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('opdata', models.CharField(blank=True, max_length=500)),
                ('zabbix_tags', models.JSONField(blank=True, default=list)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='netbox_zabbix_status.zabbixhost')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Zabbix problem',
                'verbose_name_plural': 'Zabbix problems',
                'ordering': ('-severity', '-started'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='zabbixhost',
            constraint=models.CheckConstraint(condition=models.Q(('device__isnull', True), ('virtual_machine__isnull', True), _connector='OR'), name='netbox_zabbix_status_zabbixhost_single_assignment'),
        ),
    ]
