# Generated by Django 6.0.5 on 2026-07-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_zabbix_status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('matching_enabled', models.BooleanField(default=True)),
                ('match_by_ip', models.BooleanField(default=True)),
                ('sync_vms', models.BooleanField(default=True)),
                ('hostname_strip_domains', models.JSONField(blank=True, default=list)),
                ('min_severity', models.PositiveSmallIntegerField(default=2)),
                ('cache_ttl', models.PositiveIntegerField(default=30)),
                ('dashboard_matched_only', models.BooleanField(default=True)),
                ('dashboard_refresh', models.PositiveIntegerField(default=60)),
            ],
            options={
                'verbose_name': 'Zabbix nastavenia',
                'verbose_name_plural': 'Zabbix nastavenia',
            },
        ),
    ]
