# Generated by Django 6.0.5 on 2026-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_zabbix_status', '0002_zabbixconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixconfiguration',
            name='include_suppressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zabbixproblem',
            name='suppressed',
            field=models.BooleanField(default=False),
        ),
    ]
