# Generated by Django 6.0.5 on 2026-07-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_zabbix_status', '0003_zabbixconfiguration_include_suppressed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixconfiguration',
            name='dashboard_severities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
