# Generated by Django 6.0.5 on 2026-07-09 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_zabbix_status', '0004_zabbixconfiguration_dashboard_severities'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixconfiguration',
            name='sync_interval',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
