# Generated by Django 6.0.5 on 2026-07-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_zabbix_status', '0006_zabbixconfiguration_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixproblem',
            name='zabbix_triggerid',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
