# Generated by Django 6.0.5 on 2026-07-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_zabbix_status', '0007_zabbixproblem_zabbix_triggerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixconfiguration',
            name='site_id_tag_key',
            field=models.CharField(blank=True, default='nbx_siteid', max_length=64),
        ),
    ]
