# Generated by Django 6.0.5 on 2026-07-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_zabbix_status', '0008_zabbixconfiguration_site_id_tag_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixhost',
            name='zabbix_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
