# Generated by Django 6.0.5 on 2026-07-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_zabbix_status', '0009_zabbixhost_zabbix_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixconfiguration',
            name='visible_tag_keys',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
